#!/usr/bin/env sh

cp test-input.js test-output.js

./index.js test-output.js

diff ./test-output.js ./test-expected-output.js
status=$?

# rm ./test-output.js
if [ $status -eq 0 ]; then
  echo "Success!"
  exit 0
else
  echo "Failed :("
  exit 1
fi
